package com.example.ShoppingSystem.filter.preauth.model;

import java.math.BigDecimal;
import java.util.List;

/**
 * Complete pre-auth binding stored in Redis.
 */
public record PreAuthBinding(String token,
                             String fpHash,
                             String uaHash,
                             String currentIp,
                             List<String> recentIps,
                             int changeCount,
                             int ipScore,
                             int deviceScore,
                             int score,
                             String riskLevel,
                             long currentIpSeenAtEpochMillis,
                             String currentCountry,
                             String currentRegion,
                             String currentCity,
                             BigDecimal currentLatitude,
                             BigDecimal currentLongitude,
                             int sameCityIpChangeCount,
                             String lastPenalizedIpTransition,
                             long lastPenaltyAtEpochMillis,
                             int lastPenaltyScore,
                             String lastPenaltyReason,
                             String webRtcIp,
                             String webRtcStatus,
                             long webRtcSeenAtEpochMillis,
                             int webRtcMismatchCount) {

    public PreAuthBinding(String token,
                          String fpHash,
                          String uaHash,
                          String currentIp,
                          List<String> recentIps,
                          int changeCount,
                          int ipScore,
                          int deviceScore,
                          int score,
                          String riskLevel,
                          long currentIpSeenAtEpochMillis,
                          String currentCountry,
                          String currentRegion,
                          String currentCity,
                          BigDecimal currentLatitude,
                          BigDecimal currentLongitude,
                          int sameCityIpChangeCount,
                          String lastPenalizedIpTransition,
                          long lastPenaltyAtEpochMillis,
                          int lastPenaltyScore,
                          String lastPenaltyReason) {
        this(
                token,
                fpHash,
                uaHash,
                currentIp,
                recentIps,
                changeCount,
                ipScore,
                deviceScore,
                score,
                riskLevel,
                currentIpSeenAtEpochMillis,
                currentCountry,
                currentRegion,
                currentCity,
                currentLatitude,
                currentLongitude,
                sameCityIpChangeCount,
                lastPenalizedIpTransition,
                lastPenaltyAtEpochMillis,
                lastPenaltyScore,
                lastPenaltyReason,
                "",
                "",
                0L,
                0
        );
    }

    public PreAuthBinding withWebRtcState(String nextWebRtcIp,
                                          String nextWebRtcStatus,
                                          long nextWebRtcSeenAtEpochMillis,
                                          int nextWebRtcMismatchCount) {
        return new PreAuthBinding(
                token,
                fpHash,
                uaHash,
                currentIp,
                recentIps,
                changeCount,
                ipScore,
                deviceScore,
                score,
                riskLevel,
                currentIpSeenAtEpochMillis,
                currentCountry,
                currentRegion,
                currentCity,
                currentLatitude,
                currentLongitude,
                sameCityIpChangeCount,
                lastPenalizedIpTransition,
                lastPenaltyAtEpochMillis,
                lastPenaltyScore,
                lastPenaltyReason,
                nextWebRtcIp,
                nextWebRtcStatus,
                nextWebRtcSeenAtEpochMillis,
                nextWebRtcMismatchCount
        );
    }
}
