-- 文件名：036_create_user_sign_record.sql
-- 说明：创建用户签到记录表
-- 约定：
-- 1. 一行代表一个用户在一个业务日期完成了一次签到；
-- 2. user_id 对应 user_profile.id，本字段为逻辑关联字段，不创建物理外键；
-- 3. sign_period_key 表示签到周期键，当前测试阶段按秒，正式上线时可切回按天；
-- 4. sign_date 保存签到时间，当前测试阶段精确到秒；正式上线按天时可写入当天零点；
-- 5. 同一用户同一签到周期只能签到一次，使用 user_id + sign_period_key 唯一约束保证幂等。

CREATE TABLE IF NOT EXISTS user_sign_record (
    -- 签到记录主键，由数据库自增生成
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 签到用户 ID，对应 user_profile.id；本字段为逻辑外键，不创建物理外键
    user_id BIGINT NOT NULL,

    -- 签到周期键，当前测试阶段使用 SECOND:2026-06-17T10:20:01，正式上线可切回 DAY:2026-06-17
    sign_period_key VARCHAR(32) NOT NULL,

    -- 签到时间，当前测试阶段精确到秒；正式上线按天时可写入当天零点
    sign_date TIMESTAMPTZ NOT NULL,

    -- 本次签到奖励积分
    reward_points INT NOT NULL DEFAULT 0,

    -- 本次签到后的连续签到周期数
    continuous_count INT NOT NULL DEFAULT 1,

    -- 当前 30 周期奖励循环内的周期序号，取值 1 到 30
    cycle_day INT NOT NULL DEFAULT 1,

    -- 签到记录创建时间
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_user_sign_record_user_period
        UNIQUE (user_id, sign_period_key),

    CONSTRAINT ck_user_sign_record_user_id
        CHECK (user_id > 0),

    CONSTRAINT ck_user_sign_record_period_key_not_blank
        CHECK (btrim(sign_period_key) <> ''),

    CONSTRAINT ck_user_sign_record_reward_points
        CHECK (reward_points >= 0),

    CONSTRAINT ck_user_sign_record_continuous_count
        CHECK (continuous_count > 0),

    CONSTRAINT ck_user_sign_record_cycle_day
        CHECK (cycle_day >= 1 AND cycle_day <= 30)
);

CREATE INDEX IF NOT EXISTS idx_user_sign_record_sign_date
    ON user_sign_record (sign_date);

CREATE INDEX IF NOT EXISTS idx_user_sign_record_user_latest
    ON user_sign_record (user_id, id DESC);

COMMENT ON TABLE user_sign_record IS '用户签到记录表：一行代表一个用户在一个签到周期完成了一次签到，使用 user_id + sign_period_key 唯一约束保证周期签到幂等。';

COMMENT ON COLUMN user_sign_record.id IS '签到记录主键，由数据库自增生成';
COMMENT ON COLUMN user_sign_record.user_id IS '签到用户 ID，对应 user_profile.id；本字段为逻辑外键，不创建物理外键';
COMMENT ON COLUMN user_sign_record.sign_period_key IS '签到周期键，当前测试阶段使用 SECOND:2026-06-17T10:20:01，正式上线可切回 DAY:2026-06-17，用于周期幂等判断';
COMMENT ON COLUMN user_sign_record.sign_date IS '签到时间，当前测试阶段精确到秒；正式上线按天时可写入当天零点';
COMMENT ON COLUMN user_sign_record.reward_points IS '本次签到奖励积分';
COMMENT ON COLUMN user_sign_record.continuous_count IS '本次签到后的连续签到周期数';
COMMENT ON COLUMN user_sign_record.cycle_day IS '当前 30 周期奖励循环内的周期序号，取值 1 到 30';
COMMENT ON COLUMN user_sign_record.created_at IS '签到记录创建时间';
