-- 文件名：037_create_user_point_account.sql
-- 说明：创建用户积分账户表
-- 约定：
-- 1. 一行代表一个用户的当前积分账户状态；
-- 2. user_id 对应 user_profile.id，本字段为逻辑关联字段，不创建物理外键；
-- 3. user_id 唯一约束保证一个用户只有一个积分账户；
-- 4. version 用于后续积分扣减、兑换卡密等并发场景的乐观锁控制。

CREATE TABLE IF NOT EXISTS user_point_account (
    -- 积分账户主键，由数据库自增生成
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 积分账户所属用户 ID，对应 user_profile.id；本字段为逻辑外键，不创建物理外键
    user_id BIGINT NOT NULL,

    -- 当前可用积分
    available_points BIGINT NOT NULL DEFAULT 0,

    -- 历史累计获得积分
    total_earned_points BIGINT NOT NULL DEFAULT 0,

    -- 历史累计使用积分
    total_used_points BIGINT NOT NULL DEFAULT 0,

    -- 积分账户创建时间
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- 积分账户更新时间
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- 数据版本号，用于并发积分变更时做乐观锁控制
    version BIGINT NOT NULL DEFAULT 1,

    CONSTRAINT uq_user_point_account_user_id
        UNIQUE (user_id),

    CONSTRAINT ck_user_point_account_user_id
        CHECK (user_id > 0),

    CONSTRAINT ck_user_point_account_available_points
        CHECK (available_points >= 0),

    CONSTRAINT ck_user_point_account_total_earned_points
        CHECK (total_earned_points >= 0),

    CONSTRAINT ck_user_point_account_total_used_points
        CHECK (total_used_points >= 0),

    CONSTRAINT ck_user_point_account_version
        CHECK (version > 0)
);

CREATE INDEX IF NOT EXISTS idx_user_point_account_total_earned_points
    ON user_point_account (total_earned_points DESC);

COMMENT ON TABLE user_point_account IS '用户积分账户表：保存用户当前可用积分、累计获得积分、累计使用积分和版本号，一个用户只允许一个积分账户。';

COMMENT ON COLUMN user_point_account.id IS '积分账户主键，由数据库自增生成';
COMMENT ON COLUMN user_point_account.user_id IS '积分账户所属用户 ID，对应 user_profile.id；本字段为逻辑外键，不创建物理外键';
COMMENT ON COLUMN user_point_account.available_points IS '当前可用积分';
COMMENT ON COLUMN user_point_account.total_earned_points IS '历史累计获得积分，可用于累计积分排行榜';
COMMENT ON COLUMN user_point_account.total_used_points IS '历史累计使用积分';
COMMENT ON COLUMN user_point_account.created_at IS '积分账户创建时间';
COMMENT ON COLUMN user_point_account.updated_at IS '积分账户更新时间';
COMMENT ON COLUMN user_point_account.version IS '数据版本号，用于并发积分变更时做乐观锁控制';
